### ISSUE TITLE
"Look ma, no OS! Unikernels and their applications" by Matt Bajor (video 34:25)

### ISSUE THREAD

**Issue by englishm** [ashleygwilliams/breakfast-repo#5]
Strange Loop 2015 presentation
https://www.youtube.com/watch?v=W9F4pn9Lngc

This is a pretty good overview from @technolo-g of the motivations and approaches of the current "unikernel" or "Library OS" projects.

They also put together a really awesome demo VM if you get interested and want to play around.
(Great because setting up some of the tooling for these projects can be a huge pain otherwise)
Repo: https://github.com/technolo-g/lookma

**Comment by steveklabnik** [comment]
:+1: this was great

**Comment by englishm** [comment]
Awesome! Glad you liked it. :smile:  
For a bit more about what this stuff can look like in practice (with OCaml) see @yomimono's Strange Loop 2015 talk on [Non-Imperative Network Programming](https://www.youtube.com/watch?v=GNc1t6Q5Dls) (video, 33:21).

**Comment by technolo-g** [comment]
Sweet :+1:

**Comment by ashleygwilliams** [comment]
@englishm file as another issue? that talk sounds rad. i'm p much always interested in non-imperative paradigms...
