### ISSUE TITLE
"Evidence-Oriented Programming" by Andreas Stefik Strangeloop 2015

### ISSUE THREAD

**Issue by ashleygwilliams** [ashleygwilliams/breakfast-repo#61]
https://www.youtube.com/watch?v=uEFrE6cgVNY

**Comment by englishm** [comment]
:+1: Recommended.  
Further reading on [Stefik's papers page](http://web.cs.unlv.edu/stefika/Papers.php). In particular, "The Programming Language Wars: Questions and Responsibilities for the Programming Language Community."
