### ISSUE TITLE
Reactive Podcast 11 - My Phone is Just Freaking Out

### ISSUE THREAD

**Issue by lewiscowper** [ashleygwilliams/breakfast-repo#7]
[here](http://reactive.audio/11)

A podcast in which we merge, filter, scan and map streams of thoughts and talk about software engineering, culture, and technology.

Really nice podcast as a whole. This is the latest episode. :+1:

Usually about 1 hour long, but this one is about 1:13.

**Comment by khalillechelt** [comment]
:+1: :sparkles:
